version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      #POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_MULTIPLE_DATABASES: $DB_NAME,tmp
    ports:
      - $DB_HOST:$DB_PORT:5432
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
