pg_conn_dev := postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable
pg_conn_tmp := postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/tmp?sslmode=disable
atlas := docker run --rm --net=host --volume=$(PWD)/schemas:/schemas arigaio/atlas:0.10.0-alpine


atlas-help:
	@docker run --rm arigaio/atlas:0.10.0-alpine --help


atlas-hash:
	@$(atlas) migrate hash --dir=file://schemas


# Computes the diff between the target db with the local schemas.
# We exclude the table generated by atlas to store the migration revision, atlas_schema_revisions
atlas-diff: atlas-hash
	@$(atlas) schema diff \
		--from $(pg_conn_dev) \
		--to file://schemas \
		--dev-url $(pg_conn_tmp) \
		--exclude 'atlas_schema_revisions' > diff.sql


# Applies the migration.
atlas-migrate: atlas-hash
	@$(atlas) schema apply \
		--url $(pg_conn_dev) \
		--to file://schemas \
		--dev-url $(pg_conn_tmp) \
		--exclude 'atlas_schema_revisions' \
		--auto-approve


atlas-migrate-dry-run: atlas-hash
	@$(atlas) schema apply \
		--url $(pg_conn_dev) \
		--to file://schemas \
		--dev-url $(pg_conn_tmp) \
		--exclude 'atlas_schema_revisions' \
		--dry-run


# Check database schemas.
atlas-inspect:
	@$(atlas) schema inspect --url $(pg_conn_dev) --schema public --format '{{ sql . }}'
